### PR TITLE
Commandline

### PR DESCRIPTION
**Pull request by henning-gerhardt**
Move hard coded path and file name values to command line options.

Depends on PR https://github.com/kitodo/kitodo-contrib/pull/8.

### CODE REVIEW

**Comment by henning-gerhardt** [comment]
@matthias-ronge : What did you think about this changes?

**Comment by matthias-ronge** [comment]
Basically good! Maybe you can put a comment in how a complete command line must look like. For example: There are short option names (but unlike linux also two-letter) and long option names. Which one must I use, or is it both possible? Where must be the quotes?

Something like:
```
java -jar -Dmd/path/to/goobi_metadataDisplayRules.xml [...] rulesetconverter.jar
java -jar -DmetadataDisplayRules="/path/to/goobi_metadataDisplayRules.xml" [...] rulesetconverter.jar
java -jar "--DmetadataDisplayRules=/path/to/goobi_metadataDisplayRules.xml" [...] rulesetconverter.jar
```

**Comment by henning-gerhardt** [comment]
I added a small README file with a possible application call.

**Review by matthias-ronge — APPROVED** [review]

**Comment by henning-gerhardt** [comment]
@sebastian-meyer : can this pull request be merged or is something wrong with this changes?

**Comment by sebastian-meyer** [comment]
Sorry, I missed this one.

**Comment by henning-gerhardt** [comment]
Thank you.

**Pull request merged**
