### PR TITLE
Reformat code

### PR DESCRIPTION
**Pull request by henning-gerhardt**
Made code more readable.

### CODE REVIEW

**Review by stweil — COMMENTED** [review]
Is there a recommended code formatter which everybody can use to achieve a common look of new source code?

**Comment by henning-gerhardt** [comment]
I don't know. I used default settings from IntelliJ IDEA for formating and I added a few more changes regarding to `if` and similar constructs (one line statements without curly braces).

**Review by matthias-ronge — COMMENTED** [review]
There is not really something revisable if only white were changed. I believe in the code formatter. :)

**Comment by stweil** [comment]
Looks good.

Beside code reformatting two import statements with wildcards were replaced by explicit import statements.

**Pull request merged**
